"""Add unique constraint to attendance

Revision ID: 70c97c44e748
Revises: 045cadde2a2f
Create Date: 2026-08-08 16:27:25.469440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c97c44e748'
down_revision: Union[str, Sequence[str], None] = '045cadde2a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_employee_attendance_date', 'attendances', ['employee_id', 'attendance_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_attendance_date', 'attendances', type_='unique')
    # ### end Alembic commands ###
