"""Create shifts and add shift to employees

Revision ID: 747639c4637b
Revises: 3e55348a6866
Create Date: 2026-08-08 22:51:53.000312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747639c4637b'
down_revision: Union[str, Sequence[str], None] = '3e55348a6866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('employees', sa.Column('shift_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_employees_shift_id'), 'employees', ['shift_id'], unique=False)
    op.create_foreign_key(None, 'employees', 'shifts', ['shift_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_shift_id'), table_name='employees')
    op.drop_column('employees', 'shift_id')
    op.drop_table('shifts')
    # ### end Alembic commands ###
