"""Add department id to designation

Revision ID: 7ab91b641c17
Revises: 861c2571b327
Create Date: 2026-08-10 01:58:22.409048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab91b641c17'
down_revision: Union[str, Sequence[str], None] = '861c2571b327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designations', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'designations', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'designations', type_='foreignkey')
    op.drop_column('designations', 'department_id')
    # ### end Alembic commands ###
