"""Modify check in and check out to attendances table

Revision ID: f7f1698389c5
Revises: 54ce54a3823f
Create Date: 2026-08-11 12:44:26.522659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f7f1698389c5'
down_revision: Union[str, Sequence[str], None] = '54ce54a3823f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'check_in',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(timezone=True),
               existing_nullable=True)
    op.alter_column('attendances', 'check_out',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'check_out',
               existing_type=sa.Time(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('attendances', 'check_in',
               existing_type=sa.Time(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
